GET http://localhost:3000/shortenURL
###
POST http://localhost:3000/shortenURL
Content-Type: application/json

{
    "source": "https://myaccount.google.com/u/0/?utm_source=YouTubeWeb&tab=rk&utm_medium=act&gar=WzgwLCIyMzMzODciXQ&tab=rk&hl=en"
}

###
GET http://localhost:3000/shortenURL/rqzla_SHP3w

###
DELETE http://localhost:3000/shortenURL/rqzla_SHP3w

###
PATCH http://localhost:3000/shortenURL/rqzla_SHP3w
Content-Type: application/json

{
    "source": "https://www.youtube.com/watch?v=djV11Xbc914" 
}